// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PurchaseBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	PricePaid     float32                `protobuf:"fixed32,4,opt,name=PricePaid,proto3" json:"PricePaid,omitempty"`
	TrainId       string                 `protobuf:"bytes,5,opt,name=TrainId,proto3" json:"TrainId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseBookingRequest) Reset() {
	*x = PurchaseBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseBookingRequest) ProtoMessage() {}

func (x *PurchaseBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseBookingRequest.ProtoReflect.Descriptor instead.
func (*PurchaseBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseBookingRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PurchaseBookingRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PurchaseBookingRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PurchaseBookingRequest) GetPricePaid() float32 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *PurchaseBookingRequest) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=ReceiptId,proto3" json:"ReceiptId,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	User          *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	PricePaid     float32                `protobuf:"fixed32,5,opt,name=PricePaid,proto3" json:"PricePaid,omitempty"`
	Section       string                 `protobuf:"bytes,6,opt,name=Section,proto3" json:"Section,omitempty"`
	Seat          string                 `protobuf:"bytes,7,opt,name=Seat,proto3" json:"Seat,omitempty"`
	BookingStatus string                 `protobuf:"bytes,8,opt,name=BookingStatus,proto3" json:"BookingStatus,omitempty"`
	TrainId       string                 `protobuf:"bytes,9,opt,name=TrainId,proto3" json:"TrainId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *Receipt) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *Receipt) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Receipt) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Receipt) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Receipt) GetPricePaid() float32 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *Receipt) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Receipt) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *Receipt) GetBookingStatus() string {
	if x != nil {
		return x.BookingStatus
	}
	return ""
}

func (x *Receipt) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

type PurchaseBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseBookingResponse) Reset() {
	*x = PurchaseBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseBookingResponse) ProtoMessage() {}

func (x *PurchaseBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseBookingResponse.ProtoReflect.Descriptor instead.
func (*PurchaseBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *PurchaseBookingResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type ShowReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowReceiptRequest) Reset() {
	*x = ShowReceiptRequest{}
	mi := &file_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowReceiptRequest) ProtoMessage() {}

func (x *ShowReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowReceiptRequest.ProtoReflect.Descriptor instead.
func (*ShowReceiptRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ShowReceiptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShowReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       []*Receipt             `protobuf:"bytes,1,rep,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowReceiptResponse) Reset() {
	*x = ShowReceiptResponse{}
	mi := &file_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowReceiptResponse) ProtoMessage() {}

func (x *ShowReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowReceiptResponse.ProtoReflect.Descriptor instead.
func (*ShowReceiptResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ShowReceiptResponse) GetReceipt() []*Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type GetSectionBookingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
	TrainId       string                 `protobuf:"bytes,2,opt,name=TrainId,proto3" json:"TrainId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectionBookingDetailsRequest) Reset() {
	*x = GetSectionBookingDetailsRequest{}
	mi := &file_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectionBookingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionBookingDetailsRequest) ProtoMessage() {}

func (x *GetSectionBookingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionBookingDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSectionBookingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *GetSectionBookingDetailsRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *GetSectionBookingDetailsRequest) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

type SeatBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=SeatNumber,proto3" json:"SeatNumber,omitempty"`
	SectionId     string                 `protobuf:"bytes,3,opt,name=SectionId,proto3" json:"SectionId,omitempty"`
	SectionName   string                 `protobuf:"bytes,4,opt,name=SectionName,proto3" json:"SectionName,omitempty"`
	User          *User                  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	SeatAvailable bool                   `protobuf:"varint,6,opt,name=SeatAvailable,proto3" json:"SeatAvailable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatBooking) Reset() {
	*x = SeatBooking{}
	mi := &file_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatBooking) ProtoMessage() {}

func (x *SeatBooking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatBooking.ProtoReflect.Descriptor instead.
func (*SeatBooking) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *SeatBooking) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *SeatBooking) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *SeatBooking) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *SeatBooking) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *SeatBooking) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SeatBooking) GetSeatAvailable() bool {
	if x != nil {
		return x.SeatAvailable
	}
	return false
}

type GetSectionBookingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatBookings  []*SeatBooking         `protobuf:"bytes,1,rep,name=seatBookings,proto3" json:"seatBookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectionBookingDetailsResponse) Reset() {
	*x = GetSectionBookingDetailsResponse{}
	mi := &file_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectionBookingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionBookingDetailsResponse) ProtoMessage() {}

func (x *GetSectionBookingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionBookingDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetSectionBookingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *GetSectionBookingDetailsResponse) GetSeatBookings() []*SeatBooking {
	if x != nil {
		return x.SeatBookings
	}
	return nil
}

type UpdateSeatBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=ReceiptId,proto3" json:"ReceiptId,omitempty"`
	NewSeatId     string                 `protobuf:"bytes,2,opt,name=NewSeatId,proto3" json:"NewSeatId,omitempty"`
	NewSectionId  string                 `protobuf:"bytes,3,opt,name=NewSectionId,proto3" json:"NewSectionId,omitempty"`
	NewTrainId    string                 `protobuf:"bytes,4,opt,name=NewTrainId,proto3" json:"NewTrainId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatBookingRequest) Reset() {
	*x = UpdateSeatBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatBookingRequest) ProtoMessage() {}

func (x *UpdateSeatBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeatBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSeatBookingRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *UpdateSeatBookingRequest) GetNewSeatId() string {
	if x != nil {
		return x.NewSeatId
	}
	return ""
}

func (x *UpdateSeatBookingRequest) GetNewSectionId() string {
	if x != nil {
		return x.NewSectionId
	}
	return ""
}

func (x *UpdateSeatBookingRequest) GetNewTrainId() string {
	if x != nil {
		return x.NewTrainId
	}
	return ""
}

type UpdateSeatBookingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpdatedReceipt *Receipt               `protobuf:"bytes,1,opt,name=UpdatedReceipt,proto3" json:"UpdatedReceipt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSeatBookingResponse) Reset() {
	*x = UpdateSeatBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatBookingResponse) ProtoMessage() {}

func (x *UpdateSeatBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatBookingResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeatBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSeatBookingResponse) GetUpdatedReceipt() *Receipt {
	if x != nil {
		return x.UpdatedReceipt
	}
	return nil
}

type DeleteBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=ReceiptId,proto3" json:"ReceiptId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingRequest) Reset() {
	*x = DeleteBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingRequest) ProtoMessage() {}

func (x *DeleteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBookingRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type DeleteBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeleteStatus  bool                   `protobuf:"varint,1,opt,name=DeleteStatus,proto3" json:"DeleteStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingResponse) Reset() {
	*x = DeleteBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingResponse) ProtoMessage() {}

func (x *DeleteBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBookingResponse) GetDeleteStatus() bool {
	if x != nil {
		return x.DeleteStatus
	}
	return false
}

var File_proto_booking_proto protoreflect.FileDescriptor

const file_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x13proto/booking.proto\x12\abooking\"n\n" +
	"\x04User\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x97\x01\n" +
	"\x16PurchaseBookingRequest\x12\x12\n" +
	"\x04From\x18\x01 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\tR\x02To\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\r.booking.UserR\x04user\x12\x1c\n" +
	"\tPricePaid\x18\x04 \x01(\x02R\tPricePaid\x12\x18\n" +
	"\aTrainId\x18\x05 \x01(\tR\aTrainId\"\xfa\x01\n" +
	"\aReceipt\x12\x1c\n" +
	"\tReceiptId\x18\x01 \x01(\tR\tReceiptId\x12\x12\n" +
	"\x04From\x18\x02 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x03 \x01(\tR\x02To\x12!\n" +
	"\x04user\x18\x04 \x01(\v2\r.booking.UserR\x04user\x12\x1c\n" +
	"\tPricePaid\x18\x05 \x01(\x02R\tPricePaid\x12\x18\n" +
	"\aSection\x18\x06 \x01(\tR\aSection\x12\x12\n" +
	"\x04Seat\x18\a \x01(\tR\x04Seat\x12$\n" +
	"\rBookingStatus\x18\b \x01(\tR\rBookingStatus\x12\x18\n" +
	"\aTrainId\x18\t \x01(\tR\aTrainId\"E\n" +
	"\x17PurchaseBookingResponse\x12*\n" +
	"\areceipt\x18\x01 \x01(\v2\x10.booking.ReceiptR\areceipt\",\n" +
	"\x12ShowReceiptRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x13ShowReceiptResponse\x12*\n" +
	"\areceipt\x18\x01 \x03(\v2\x10.booking.ReceiptR\areceipt\"Y\n" +
	"\x1fGetSectionBookingDetailsRequest\x12\x1c\n" +
	"\tsectionId\x18\x01 \x01(\tR\tsectionId\x12\x18\n" +
	"\aTrainId\x18\x02 \x01(\tR\aTrainId\"\xce\x01\n" +
	"\vSeatBooking\x12\x16\n" +
	"\x06seatId\x18\x01 \x01(\tR\x06seatId\x12\x1e\n" +
	"\n" +
	"SeatNumber\x18\x02 \x01(\tR\n" +
	"SeatNumber\x12\x1c\n" +
	"\tSectionId\x18\x03 \x01(\tR\tSectionId\x12 \n" +
	"\vSectionName\x18\x04 \x01(\tR\vSectionName\x12!\n" +
	"\x04user\x18\x05 \x01(\v2\r.booking.UserR\x04user\x12$\n" +
	"\rSeatAvailable\x18\x06 \x01(\bR\rSeatAvailable\"\\\n" +
	" GetSectionBookingDetailsResponse\x128\n" +
	"\fseatBookings\x18\x01 \x03(\v2\x14.booking.SeatBookingR\fseatBookings\"\x9a\x01\n" +
	"\x18UpdateSeatBookingRequest\x12\x1c\n" +
	"\tReceiptId\x18\x01 \x01(\tR\tReceiptId\x12\x1c\n" +
	"\tNewSeatId\x18\x02 \x01(\tR\tNewSeatId\x12\"\n" +
	"\fNewSectionId\x18\x03 \x01(\tR\fNewSectionId\x12\x1e\n" +
	"\n" +
	"NewTrainId\x18\x04 \x01(\tR\n" +
	"NewTrainId\"U\n" +
	"\x19UpdateSeatBookingResponse\x128\n" +
	"\x0eUpdatedReceipt\x18\x01 \x01(\v2\x10.booking.ReceiptR\x0eUpdatedReceipt\"4\n" +
	"\x14DeleteBookingRequest\x12\x1c\n" +
	"\tReceiptId\x18\x01 \x01(\tR\tReceiptId\";\n" +
	"\x15DeleteBookingResponse\x12\"\n" +
	"\fDeleteStatus\x18\x01 \x01(\bR\fDeleteStatus2\xcd\x03\n" +
	"\x0eBookingService\x12T\n" +
	"\x0fPurchaseBooking\x12\x1f.booking.PurchaseBookingRequest\x1a .booking.PurchaseBookingResponse\x12H\n" +
	"\vShowReceipt\x12\x1b.booking.ShowReceiptRequest\x1a\x1c.booking.ShowReceiptResponse\x12o\n" +
	"\x18GetSectionBookingDetails\x12(.booking.GetSectionBookingDetailsRequest\x1a).booking.GetSectionBookingDetailsResponse\x12Z\n" +
	"\x11UpdateSeatBooking\x12!.booking.UpdateSeatBookingRequest\x1a\".booking.UpdateSeatBookingResponse\x12N\n" +
	"\rDeleteBooking\x12\x1d.booking.DeleteBookingRequest\x1a\x1e.booking.DeleteBookingResponseB\x16Z\x14grpc-project/bookingb\x06proto3"

var (
	file_proto_booking_proto_rawDescOnce sync.Once
	file_proto_booking_proto_rawDescData []byte
)

func file_proto_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)))
	})
	return file_proto_booking_proto_rawDescData
}

var file_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_booking_proto_goTypes = []any{
	(*User)(nil),                             // 0: booking.User
	(*PurchaseBookingRequest)(nil),           // 1: booking.PurchaseBookingRequest
	(*Receipt)(nil),                          // 2: booking.Receipt
	(*PurchaseBookingResponse)(nil),          // 3: booking.PurchaseBookingResponse
	(*ShowReceiptRequest)(nil),               // 4: booking.ShowReceiptRequest
	(*ShowReceiptResponse)(nil),              // 5: booking.ShowReceiptResponse
	(*GetSectionBookingDetailsRequest)(nil),  // 6: booking.GetSectionBookingDetailsRequest
	(*SeatBooking)(nil),                      // 7: booking.SeatBooking
	(*GetSectionBookingDetailsResponse)(nil), // 8: booking.GetSectionBookingDetailsResponse
	(*UpdateSeatBookingRequest)(nil),         // 9: booking.UpdateSeatBookingRequest
	(*UpdateSeatBookingResponse)(nil),        // 10: booking.UpdateSeatBookingResponse
	(*DeleteBookingRequest)(nil),             // 11: booking.DeleteBookingRequest
	(*DeleteBookingResponse)(nil),            // 12: booking.DeleteBookingResponse
}
var file_proto_booking_proto_depIdxs = []int32{
	0,  // 0: booking.PurchaseBookingRequest.user:type_name -> booking.User
	0,  // 1: booking.Receipt.user:type_name -> booking.User
	2,  // 2: booking.PurchaseBookingResponse.receipt:type_name -> booking.Receipt
	2,  // 3: booking.ShowReceiptResponse.receipt:type_name -> booking.Receipt
	0,  // 4: booking.SeatBooking.user:type_name -> booking.User
	7,  // 5: booking.GetSectionBookingDetailsResponse.seatBookings:type_name -> booking.SeatBooking
	2,  // 6: booking.UpdateSeatBookingResponse.UpdatedReceipt:type_name -> booking.Receipt
	1,  // 7: booking.BookingService.PurchaseBooking:input_type -> booking.PurchaseBookingRequest
	4,  // 8: booking.BookingService.ShowReceipt:input_type -> booking.ShowReceiptRequest
	6,  // 9: booking.BookingService.GetSectionBookingDetails:input_type -> booking.GetSectionBookingDetailsRequest
	9,  // 10: booking.BookingService.UpdateSeatBooking:input_type -> booking.UpdateSeatBookingRequest
	11, // 11: booking.BookingService.DeleteBooking:input_type -> booking.DeleteBookingRequest
	3,  // 12: booking.BookingService.PurchaseBooking:output_type -> booking.PurchaseBookingResponse
	5,  // 13: booking.BookingService.ShowReceipt:output_type -> booking.ShowReceiptResponse
	8,  // 14: booking.BookingService.GetSectionBookingDetails:output_type -> booking.GetSectionBookingDetailsResponse
	10, // 15: booking.BookingService.UpdateSeatBooking:output_type -> booking.UpdateSeatBookingResponse
	12, // 16: booking.BookingService.DeleteBooking:output_type -> booking.DeleteBookingResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_booking_proto_init() }
func file_proto_booking_proto_init() {
	if File_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_proto = out.File
	file_proto_booking_proto_goTypes = nil
	file_proto_booking_proto_depIdxs = nil
}
