// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/booking.proto

package booking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingService_PurchaseBooking_FullMethodName          = "/booking.BookingService/PurchaseBooking"
	BookingService_ShowReceipt_FullMethodName              = "/booking.BookingService/ShowReceipt"
	BookingService_GetSectionBookingDetails_FullMethodName = "/booking.BookingService/GetSectionBookingDetails"
	BookingService_UpdateSeatBooking_FullMethodName        = "/booking.BookingService/UpdateSeatBooking"
	BookingService_DeleteBooking_FullMethodName            = "/booking.BookingService/DeleteBooking"
)

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingServiceClient interface {
	PurchaseBooking(ctx context.Context, in *PurchaseBookingRequest, opts ...grpc.CallOption) (*PurchaseBookingResponse, error)
	ShowReceipt(ctx context.Context, in *ShowReceiptRequest, opts ...grpc.CallOption) (*ShowReceiptResponse, error)
	GetSectionBookingDetails(ctx context.Context, in *GetSectionBookingDetailsRequest, opts ...grpc.CallOption) (*GetSectionBookingDetailsResponse, error)
	UpdateSeatBooking(ctx context.Context, in *UpdateSeatBookingRequest, opts ...grpc.CallOption) (*UpdateSeatBookingResponse, error)
	DeleteBooking(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error)
}

type bookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingServiceClient(cc grpc.ClientConnInterface) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) PurchaseBooking(ctx context.Context, in *PurchaseBookingRequest, opts ...grpc.CallOption) (*PurchaseBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseBookingResponse)
	err := c.cc.Invoke(ctx, BookingService_PurchaseBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) ShowReceipt(ctx context.Context, in *ShowReceiptRequest, opts ...grpc.CallOption) (*ShowReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowReceiptResponse)
	err := c.cc.Invoke(ctx, BookingService_ShowReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) GetSectionBookingDetails(ctx context.Context, in *GetSectionBookingDetailsRequest, opts ...grpc.CallOption) (*GetSectionBookingDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSectionBookingDetailsResponse)
	err := c.cc.Invoke(ctx, BookingService_GetSectionBookingDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) UpdateSeatBooking(ctx context.Context, in *UpdateSeatBookingRequest, opts ...grpc.CallOption) (*UpdateSeatBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSeatBookingResponse)
	err := c.cc.Invoke(ctx, BookingService_UpdateSeatBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) DeleteBooking(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBookingResponse)
	err := c.cc.Invoke(ctx, BookingService_DeleteBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
// All implementations must embed UnimplementedBookingServiceServer
// for forward compatibility.
type BookingServiceServer interface {
	PurchaseBooking(context.Context, *PurchaseBookingRequest) (*PurchaseBookingResponse, error)
	ShowReceipt(context.Context, *ShowReceiptRequest) (*ShowReceiptResponse, error)
	GetSectionBookingDetails(context.Context, *GetSectionBookingDetailsRequest) (*GetSectionBookingDetailsResponse, error)
	UpdateSeatBooking(context.Context, *UpdateSeatBookingRequest) (*UpdateSeatBookingResponse, error)
	DeleteBooking(context.Context, *DeleteBookingRequest) (*DeleteBookingResponse, error)
	mustEmbedUnimplementedBookingServiceServer()
}

// UnimplementedBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingServiceServer struct{}

func (UnimplementedBookingServiceServer) PurchaseBooking(context.Context, *PurchaseBookingRequest) (*PurchaseBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseBooking not implemented")
}
func (UnimplementedBookingServiceServer) ShowReceipt(context.Context, *ShowReceiptRequest) (*ShowReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowReceipt not implemented")
}
func (UnimplementedBookingServiceServer) GetSectionBookingDetails(context.Context, *GetSectionBookingDetailsRequest) (*GetSectionBookingDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSectionBookingDetails not implemented")
}
func (UnimplementedBookingServiceServer) UpdateSeatBooking(context.Context, *UpdateSeatBookingRequest) (*UpdateSeatBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSeatBooking not implemented")
}
func (UnimplementedBookingServiceServer) DeleteBooking(context.Context, *DeleteBookingRequest) (*DeleteBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBooking not implemented")
}
func (UnimplementedBookingServiceServer) mustEmbedUnimplementedBookingServiceServer() {}
func (UnimplementedBookingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServiceServer will
// result in compilation errors.
type UnsafeBookingServiceServer interface {
	mustEmbedUnimplementedBookingServiceServer()
}

func RegisterBookingServiceServer(s grpc.ServiceRegistrar, srv BookingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingService_ServiceDesc, srv)
}

func _BookingService_PurchaseBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).PurchaseBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_PurchaseBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).PurchaseBooking(ctx, req.(*PurchaseBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_ShowReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).ShowReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_ShowReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).ShowReceipt(ctx, req.(*ShowReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_GetSectionBookingDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSectionBookingDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetSectionBookingDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_GetSectionBookingDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetSectionBookingDetails(ctx, req.(*GetSectionBookingDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_UpdateSeatBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSeatBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).UpdateSeatBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_UpdateSeatBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).UpdateSeatBooking(ctx, req.(*UpdateSeatBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_DeleteBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).DeleteBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_DeleteBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).DeleteBooking(ctx, req.(*DeleteBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingService_ServiceDesc is the grpc.ServiceDesc for BookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurchaseBooking",
			Handler:    _BookingService_PurchaseBooking_Handler,
		},
		{
			MethodName: "ShowReceipt",
			Handler:    _BookingService_ShowReceipt_Handler,
		},
		{
			MethodName: "GetSectionBookingDetails",
			Handler:    _BookingService_GetSectionBookingDetails_Handler,
		},
		{
			MethodName: "UpdateSeatBooking",
			Handler:    _BookingService_UpdateSeatBooking_Handler,
		},
		{
			MethodName: "DeleteBooking",
			Handler:    _BookingService_DeleteBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/booking.proto",
}
